os:
  - linux

env:
  - ARCH="i686"

language: python

python:
  - "2.7"

# command to install dependencies
install:
  - "pip install pytest"
  - "pip install pytest-raisesregexp"

# command to run tests
script: make