language: python

python:
  - "3.6"

# command to install dependencies
install:
  - "pip install flake8"
  - "pip install pytest"
  - "pip install pytest-raisesregexp"

# command to run tests
script:
  - flake8
  - make
